//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtikujApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Emertimi { get; set; }
        public string Barkod { get; set; }
        public Nullable<System.DateTime> DataSkadences { get; set; }
        public decimal Cmimi { get; set; }
        public bool KaTvsh { get; set; }
        public int LlojID { get; set; }
        public int TipiID { get; set; }
        public int NjesiaID { get; set; }
    
        public virtual Lloj Lloj { get; set; }
        public virtual Njesia Njesia { get; set; }
        public virtual Tipi Tipi { get; set; }
    }
}
